# Generated by Django 2.0.1 on 2018-01-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('stress_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='percentadded',
            field=models.IntegerField(default=0),
        ),
    ]
